import sqlite3
from pathlib import Path

import pandas as pd


# =========================================================
# DATABASE CONFIGURATION
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent

DATABASE_PATH = BASE_DIR / "database" / "business.db"


# =========================================================
# DATABASE CONNECTION
# =========================================================

def get_connection():
    """
    Create and return a connection to the SQLite database.
    """

    return sqlite3.connect(DATABASE_PATH)


# =========================================================
# 1. TOTAL REVENUE
# =========================================================

def get_total_revenue():
    """
    Calculate total revenue across all orders.

    Returns:
        float: Total revenue
    """

    query = """
    SELECT
        SUM(revenue) AS total_revenue
    FROM orders;
    """

    connection = get_connection()

    try:
        result = pd.read_sql_query(
            query,
            connection
        )

        return result.loc[0, "total_revenue"]

    finally:
        connection.close()


# =========================================================
# 2. MONTHLY REVENUE
# =========================================================

def get_monthly_revenue():
    """
    Calculate revenue for each month.

    Returns:
        pandas.DataFrame:
            month
            revenue
    """

    query = """
    SELECT
        strftime('%m', order_date) AS month,
        SUM(revenue) AS revenue
    FROM orders
    GROUP BY month
    ORDER BY month;
    """

    connection = get_connection()

    try:
        result = pd.read_sql_query(
            query,
            connection
        )

        return result

    finally:
        connection.close()


# =========================================================
# 3. REVENUE BY CATEGORY
# =========================================================

def get_revenue_by_category():
    """
    Calculate revenue for each product category.

    Returns:
        pandas.DataFrame:
            category
            revenue
    """

    query = """
    SELECT
        category,
        SUM(revenue) AS revenue
    FROM orders
    GROUP BY category
    ORDER BY revenue DESC;
    """

    connection = get_connection()

    try:
        result = pd.read_sql_query(
            query,
            connection
        )

        return result

    finally:
        connection.close()


# =========================================================
# 4. REVENUE BY CUSTOMER
# =========================================================

def get_revenue_by_customer():
    """
    Calculate total revenue generated by each customer.

    Returns:
        pandas.DataFrame:
            customer_id
            revenue
    """

    query = """
    SELECT
        customer_id,
        SUM(revenue) AS revenue
    FROM orders
    GROUP BY customer_id
    ORDER BY revenue DESC;
    """

    connection = get_connection()

    try:
        result = pd.read_sql_query(
            query,
            connection
        )

        return result

    finally:
        connection.close()


# =========================================================
# 5. REVENUE BY REGION
# =========================================================

def get_revenue_by_region():
    """
    Calculate revenue for each customer region.

    Returns:
        pandas.DataFrame:
            region
            revenue
    """

    query = """
    SELECT
        c.region,
        SUM(o.revenue) AS revenue

    FROM orders o

    JOIN customers c
        ON o.customer_id = c.customer_id

    GROUP BY c.region

    ORDER BY revenue DESC;
    """

    connection = get_connection()

    try:
        result = pd.read_sql_query(
            query,
            connection
        )

        return result

    finally:
        connection.close()


# =========================================================
# 6. AVERAGE ORDER VALUE
# =========================================================

def get_average_order_value():
    """
    Calculate the average revenue per order.

    Returns:
        float: Average order value
    """

    query = """
    SELECT
        AVG(revenue) AS average_order_value
    FROM orders;
    """

    connection = get_connection()

    try:
        result = pd.read_sql_query(
            query,
            connection
        )

        return result.loc[0, "average_order_value"]

    finally:
        connection.close()


# =========================================================
# 7. FEBRUARY VS MARCH REVENUE
# =========================================================

def get_february_march_revenue():
    """
    Compare total February revenue with
    total March revenue.

    Returns:
        pandas.DataFrame:
            february_revenue
            march_revenue
            percentage_change
    """

    query = """
    SELECT

        (
            SELECT SUM(revenue)
            FROM orders
            WHERE strftime('%m', order_date) = '02'
        ) AS february_revenue,

        (
            SELECT SUM(revenue)
            FROM orders
            WHERE strftime('%m', order_date) = '03'
        ) AS march_revenue;
    """

    connection = get_connection()

    try:

        result = pd.read_sql_query(
            query,
            connection
        )

        february_revenue = result.loc[
            0,
            "february_revenue"
        ]

        march_revenue = result.loc[
            0,
            "march_revenue"
        ]

        percentage_change = (
            (
                march_revenue
                - february_revenue
            )
            / february_revenue
        ) * 100

        result["percentage_change"] = (
            percentage_change
        )

        return result

    finally:
        connection.close()


# =========================================================
# 8. FEBRUARY VS MARCH BY CATEGORY
# =========================================================

def get_category_month_comparison():
    """
    Compare February and March revenue
    for every product category.

    Returns:
        pandas.DataFrame:
            category
            february_revenue
            march_revenue
            revenue_change
            percentage_change
    """

    query = """
    SELECT

        category,

        SUM(
            CASE
                WHEN strftime('%m', order_date) = '02'
                THEN revenue
                ELSE 0
            END
        ) AS february_revenue,

        SUM(
            CASE
                WHEN strftime('%m', order_date) = '03'
                THEN revenue
                ELSE 0
            END
        ) AS march_revenue

    FROM orders

    WHERE strftime('%m', order_date)
        IN ('02', '03')

    GROUP BY category

    ORDER BY
        march_revenue - february_revenue;
    """

    connection = get_connection()

    try:

        result = pd.read_sql_query(
            query,
            connection
        )

        result["revenue_change"] = (
            result["march_revenue"]
            - result["february_revenue"]
        )

        result["percentage_change"] = (
            result["revenue_change"]
            / result["february_revenue"]
        ) * 100

        return result

    finally:
        connection.close()


# =========================================================
# TEST ALL FUNCTIONS
# =========================================================

if __name__ == "__main__":

    print("=" * 60)
    print("SQL ANALYSIS LAYER")
    print("=" * 60)


    # -----------------------------------------------------
    # Total Revenue
    # -----------------------------------------------------

    print("\nTOTAL REVENUE")

    total_revenue = get_total_revenue()

    print(
        f"${total_revenue:,.2f}"
    )


    # -----------------------------------------------------
    # Monthly Revenue
    # -----------------------------------------------------

    print("\nMONTHLY REVENUE")

    monthly_revenue = get_monthly_revenue()

    print(monthly_revenue.to_string(index=False))


    # -----------------------------------------------------
    # Revenue by Category
    # -----------------------------------------------------

    print("\nREVENUE BY CATEGORY")

    category_revenue = get_revenue_by_category()

    print(category_revenue.to_string(index=False))


    # -----------------------------------------------------
    # Top Customers
    # -----------------------------------------------------

    print("\nTOP 10 CUSTOMERS")

    customer_revenue = get_revenue_by_customer()

    print(
        customer_revenue
        .head(10)
        .to_string(index=False)
    )


    # -----------------------------------------------------
    # Revenue by Region
    # -----------------------------------------------------

    print("\nREVENUE BY REGION")

    region_revenue = get_revenue_by_region()

    print(region_revenue.to_string(index=False))


    # -----------------------------------------------------
    # Average Order Value
    # -----------------------------------------------------

    print("\nAVERAGE ORDER VALUE")

    average_order_value = (
        get_average_order_value()
    )

    print(
        f"${average_order_value:,.2f}"
    )


    # -----------------------------------------------------
    # February vs March
    # -----------------------------------------------------

    print("\nFEBRUARY VS MARCH")

    february_march = (
        get_february_march_revenue()
    )

    print(
        february_march.to_string(
            index=False
        )
    )


    # -----------------------------------------------------
    # February vs March by Category
    # -----------------------------------------------------

    print(
        "\nFEBRUARY VS MARCH BY CATEGORY"
    )

    category_comparison = (
        get_category_month_comparison()
    )

    print(
        category_comparison.to_string(
            index=False
        )
    )


    # -----------------------------------------------------
    # Finished
    # -----------------------------------------------------

    print("\n" + "=" * 60)
    print("ANALYSIS COMPLETE")
    print("=" * 60)